function res=fig_static(x,config)
figure();
plot(x.time, ...
     remean(x.op1), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP1');hold on;
plot(x.time, ...
     remean(x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'DC');hold on;
plot(x.time, ...
     remean(x.op1-x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP1-DC');hold on;
grid on; hold on; box on;
xlabel('Time (s)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
ylabel('B (nT)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
legend('show', ...
    'Location', 'best', ...
    'FontSize', config.fig.legendSize,'FontWeight','Bold');
createFigure(config.fig);
title('Static', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
print(fullfile(config.respath, 'static op1'), '-dpng', sprintf('-r%d', config.fig.dpi));


res = get_static_noise(x.op1, config.fs, config.radio);
fprintf('OP1 Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );
res =get_static_noise(x.op1-x.DC, config.fs, config.radio);
fprintf('OP1-DC Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );

figure();
plot(x.time, ...
     remean(x.op2), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP2');hold on;
plot(x.time, ...
     remean(x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'DC');hold on;
plot(x.time, ...
     remean(x.op2-x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP2-DC');hold on;
grid on; hold on; box on;
xlabel('Time (s)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
ylabel('B (nT)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
legend('show', ...
    'Location', 'best', ...
    'FontSize', config.fig.legendSize,'FontWeight','Bold');
title('Static', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
createFigure(config.fig);
print(fullfile(config.respath, 'static op2'), '-dpng', sprintf('-r%d', config.fig.dpi));


res =get_static_noise(x.op2, config.fs, config.radio);
fprintf('OP2 Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );
res =get_static_noise(x.op2-x.DC, config.fs, config.radio);
fprintf('OP2-DC Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );

res =get_static_noise(x.ddop, config.fs, config.radio);
fprintf('ddop Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );
res =get_static_noise(x.ddop-x.DC, config.fs, config.radio);
fprintf('ddop-DC Static noise： Sn = %f nT    rSn = %f nT\n', ...
    res.static.std,res.static.file_std );
end