function res=fig_dynamic(x,config)
figure;

plot(x.time, ...
     remean(x.op1), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP1');hold on;
plot(x.time, ...
     remean(x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'DC');
plot(x.time, ...
     remean(x.op1-x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP1-DC');hold on;
grid on; hold on; box on;
xlabel('Time (s)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
ylabel('B (nT)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
legend('show', ...
    'Location', 'best', ...
    'FontSize', config.fig.legendSize,'FontWeight','Bold');
createFigure(config.fig);
title('Dynamic', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
res =get_dynamic_noise(x.op1, config.fs, config.radio);
fprintf('OP1 Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );
res =get_dynamic_noise(x.op1-x.DC, config.fs, config.radio);
fprintf('OP1-DC Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );
print(fullfile(config.respath, 'dynamic op1'), '-dpng', sprintf('-r%d', config.fig.dpi));

figure;
plot(x.time, ...
     remean(x.op2), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP2');hold on;
plot(x.time, ...
     remean(x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'DC');
plot(x.time, ...
     remean(x.op2-x.DC), ...
     'LineWidth', config.fig.lineWidth, ...
     'DisplayName', 'OP2-DC');hold on;
grid on; hold on; box on;
xlabel('Time (s)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
ylabel('B (nT)', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
legend('show', ...
    'Location', 'best', ...
    'FontSize', config.fig.legendSize,'FontWeight','Bold');
title('Dynamic', 'FontSize', config.fig.labelSize,'FontWeight','Bold');
createFigure(config.fig);
print(fullfile(config.respath, 'dynamic op2'), '-dpng', sprintf('-r%d', config.fig.dpi));

res =get_dynamic_noise(x.op2, config.fs, config.radio);
fprintf('OP2 Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );
res =get_dynamic_noise(x.op2-x.DC, config.fs, config.radio);
fprintf('OP2-DC Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );

res =get_dynamic_noise(x.ddop, config.fs, config.radio);
fprintf('ddop Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );
res =get_dynamic_noise(x.ddop-x.DC, config.fs, config.radio);
fprintf('ddop-DC Dynamic noise： Sn = %f nT    rSn = %f nT\n', ...
    res.dynamic.std,res.dynamic.file_std );

end